skdep/force-app/main/default/objects/Monitor_Log__c/Monitor_Log__c.object-meta.xml
<CustomObject>
    <label>Monitor Log</label>
    <nameField>
        <label>Monitor Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monitor Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/All_Module__c.field-meta.xml
<CustomField>
    <fullName>All_Module__c</fullName>
    <defaultValue>true</defaultValue>
    <label>All Module</label>
    <type>Checkbox</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <label>Apex Class</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Concern__c.field-meta.xml
<CustomField>
    <fullName>Concern__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Concern</label>
    <type>Checkbox</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Concern_Person__c.field-meta.xml
<CustomField>
    <fullName>Concern_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Concern Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Monitor_Logs1</relationshipName>
    <type>Lookup</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Data_Source__c.field-meta.xml
<CustomField>
    <fullName>Data_Source__c</fullName>
    <label>Data Source</label>
    <type>TextArea</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Except_Module_Log__c.field-meta.xml
<CustomField>
    <fullName>Except_Module_Log__c</fullName>
    <label>Except Module Log</label>
    <type>TextArea</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/External_System_Name__c.field-meta.xml
<CustomField>
    <fullName>External_System_Name__c</fullName>
    <label>External System Name</label>
    <type>TextArea</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <label>Headers</label>
    <type>TextArea</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Keep_log_for_last_X_days__c.field-meta.xml
<CustomField>
    <fullName>Keep_log_for_last_X_days__c</fullName>
    <label>Keep log for last X days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Loggin_User__c.field-meta.xml
<CustomField>
    <fullName>Loggin_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loggin User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Monitor_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Logging_Type__c.field-meta.xml
<CustomField>
    <fullName>Logging_Type__c</fullName>
    <label>Logging Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warnning</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Login_User_Name__c.field-meta.xml
<CustomField>
    <fullName>Login_User_Name__c</fullName>
    <formula>Loggin_User__r.FirstName  +&apos; &apos;+ Loggin_User__r.LastName</formula>
    <label>Login User Name</label>
    <type>Text</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Notification__c.field-meta.xml
<CustomField>
    <fullName>Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notification</label>
    <type>Checkbox</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Notification_Email__c.field-meta.xml
<CustomField>
    <fullName>Notification_Email__c</fullName>
    <label>Notification Email</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Purged_file_Name__c.field-meta.xml
<CustomField>
    <fullName>Purged_file_Name__c</fullName>
    <label>Purged file Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Purged_Status__c.field-meta.xml
<CustomField>
    <fullName>Purged_Status__c</fullName>
    <label>Purged Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Purging_Mode__c.field-meta.xml
<CustomField>
    <fullName>Purging_Mode__c</fullName>
    <label>Purging Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual</fullName>
                <default>true</default>
                <label>Manual</label>
            </value>
            <value>
                <fullName>Auto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Purging_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Purging_Schedule__c</fullName>
    <label>Purging Schedule</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/ReloadStatus__c.field-meta.xml
<CustomField>
    <fullName>ReloadStatus__c</fullName>
    <label>Reload Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Start</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Remote_Address__c.field-meta.xml
<CustomField>
    <fullName>Remote_Address__c</fullName>
    <label>Remote Address</label>
    <type>TextArea</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Request_JSON__c.field-meta.xml
<CustomField>
    <fullName>Request_JSON__c</fullName>
    <label>Request JSON</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Request_URL__c.field-meta.xml
<CustomField>
    <fullName>Request_URL__c</fullName>
    <label>Request URL</label>
    <type>TextArea</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Response_JSON__c.field-meta.xml
<CustomField>
    <fullName>Response_JSON__c</fullName>
    <label>Response JSON</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Schedule_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Job_Id__c</fullName>
    <label>Schedule Job Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <label>Status Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Terms_Condition__c.field-meta.xml
<CustomField>
    <fullName>Terms_Condition__c</fullName>
    <label>Terms &amp; Condition</label>
    <type>TextArea</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Type_Of_Integration__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Integration__c</fullName>
    <label>Type Of Integration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

skdep/force-app/main/default/classes/MonitorSelector.cls
/**
 * @description       : This class show all Query of Monitor object.                                          
 * @author            : prashant.kumbhar@skinternational.com
 * @last modified on  : 10-11-2023
 * @last modified by  :  prashant.kumbhar@skinternational.com
**/


public class MonitorSelector extends LibSObjectSelector {
    
    public Schema.SObjectType getSObjectType(){
        return Monitor_Log__c.SObjectType;
    }
    
/**
* @description:This method is used to define all the fields of Object.
* @return List<Schema.SObjectField>
*/ 
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
                Monitor_Log__c.Id,
                Monitor_Log__c.Name,
                Monitor_Log__c.All_Module__c,
                Monitor_Log__c.Apex_Class__c,
                Monitor_Log__c.Concern__c,
                Monitor_Log__c.Concern_Person__c,    
                Monitor_Log__c.Data_Source__c,
                Monitor_Log__c.Date_Time__c,   
                Monitor_Log__c.Error_Message__c,
                Monitor_Log__c.Except_Module_Log__c,
                Monitor_Log__c.External_System_Name__c,
                Monitor_Log__c.Headers__c,
                Monitor_Log__c.Keep_log_for_last_X_days__c,    
                Monitor_Log__c.Logging_Type__c,
                Monitor_Log__c.Loggin_User__c,
                Monitor_Log__c.Login_User_Name__c	,
                Monitor_Log__c.Method__c,
                Monitor_Log__c.Module__c,
                Monitor_Log__c.Notification__c,
                Monitor_Log__c.Notification_Email__c,    
                Monitor_Log__c.Purged_file_Name__c,
                Monitor_Log__c.Purged_Status__c,   
                Monitor_Log__c.Purging_Mode__c,
                Monitor_Log__c.Purging_Schedule__c	,
                Monitor_Log__c.RecordId__c,
                Monitor_Log__c.Record_Type__c,
                Monitor_Log__c.ReloadStatus__c,    
                Monitor_Log__c.Remote_Address__c,
                Monitor_Log__c.Request_JSON__c,      
                Monitor_Log__c.Request_URL__c,
                Monitor_Log__c.Response_JSON__c	,
                Monitor_Log__c.Schedule_Job_Id__c,
                Monitor_Log__c.Status__c,
                Monitor_Log__c.Status_Code__c,    
                Monitor_Log__c.Terms_Condition__c,
                Monitor_Log__c.Type_Of_Integration__c
                };
                    }

}