skdep/force-app/main/default/objects/Monitor_Log__c/Monitor_Log__c.object-meta.xml
<CustomObject>
    <label>Monitor Log</label>
    <nameField>
        <label>Monitor Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monitor Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Concern_Person__c.field-meta.xml
<CustomField>
    <fullName>Concern_Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Concern Person</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Monitor_Logs1</relationshipName>
    <type>Lookup</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Purged_Status__c.field-meta.xml
<CustomField>
    <fullName>Purged_Status__c</fullName>
    <label>Purged Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Purging_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Purging_Schedule__c</fullName>
    <label>Purging Schedule</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/ReloadStatus__c.field-meta.xml
<CustomField>
    <fullName>ReloadStatus__c</fullName>
    <label>Reload Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Start</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/fields/Schedule_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Job_Id__c</fullName>
    <label>Schedule Job Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

skdep/force-app/main/default/objects/Monitor_Log__c/recordTypes/Log.recordType-meta.xml
<RecordType>
    <fullName>Log</fullName>
    <active>true</active>
    <label>Log</label>
</RecordType>

skdep/force-app/main/default/objects/Monitor_Log__c/recordTypes/Scheduler.recordType-meta.xml
<RecordType>
    <fullName>Scheduler</fullName>
    <active>true</active>
    <label>Scheduler</label>
</RecordType>

skdep/force-app/main/default/classes/MonitorLogHandler.cls
/**
 * @description       : This handler is used to start Scheduler based on specific criteria.                                          
 * @author            : prashant.kumbhar@skinternational.com
 * @last modified on  : 06-23-2023
 * @last modified by  :  prashant.kumbhar@skinternational.com
**/


public class MonitorLogHandler {
    
    MonitorLogGenerateFile scheduledJob = new MonitorLogGenerateFile();
    String jobId='';
    String recordtypeId= Schema.SObjectType.Monitor_Log__c.getRecordTypeInfosByName().get('Scheduler').getRecordTypeId();
    String userId=userInfo.getUserId();
    String monitorId='';
    
/** 
* @Description - This method is Used to Update Job Id of records. 
* @param m :Monitor Log.
* @return  -    void
*/       
    public void beforeInsert(List<Monitor_Log__c> m){        
        for(Monitor_Log__c monitor:m)
        {
            if(monitor.Status__c==true && monitor.Purging_Schedule__c!=null && monitor.RecordTypeId==recordtypeId)
            {
                jobId= System.schedule(monitor.Name, monitor.Purging_Schedule__c,scheduledJob);
                monitor.Schedule_Job_Id__c=jobId;  
                monitor.Purged_Status__c='In Progress';
                monitor.Concern_Person__c=userId;               
            }      
        }     
    }

/** 
* @description - This method is Used to Update Job Id and Status of records on After Insert Event. 
* @param n :Monitor Log.
* @return  -    void
*/    
    public void afterInsert(List<Monitor_Log__c> n){
        for(Monitor_Log__c monitor1:n)
        {
            if(monitor1.Status__c==false && monitor1.Schedule_Job_Id__c !=null)
            {
                monitor1.Schedule_Job_Id__c='';                 
            }   
            if(monitor1.ReloadStatus__c=='Start' && monitor1.Schedule_Job_Id__c !=null)
            { 
                monitorId=monitor1.id;
                //MonitorService x=new MonitorService();
                MonitorService.reloadRecords(monitorId);
            }     
            else if(monitor1.ReloadStatus__c=='Start' && monitor1.Schedule_Job_Id__c ==null)
             {
                    monitor1.addError('Scheduled Job is Blank');
             }
        }     
    }
    
}